# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: true
enable_free_tier: true
knowledge_base:
  code_guidelines:
    enabled: true
    filePatterns:
      - "AGENTS.md"
      - ".github/CONTRIBUTING.md"
reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  review_status: true
  fail_commit_status: false
  collapse_walkthrough: false
  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: false
  pre_merge_checks:
    title:
      mode: "error"
      requirements: "Use Conventional Commits: type(scope)!?: subject — types: feat, fix, docs, style, refactor, perf, test, chore, build, ci, revert; for revert: reference the reverted commit; no period at the end."
    description:
      mode: "warning"
    docstrings:
      mode: "off"
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - "main"
      - "develop"
    auto_incremental_review: true
    ignore_usernames:
      - "renovate[bot]"
      - "dependabot[bot]"
      - "github-actions[bot]"
  tools:
    eslint:
      enabled: true
chat:
  auto_reply: true
