packages:
  - '.'
  - 'packages/schemas'

overrides:
  conventional-changelog-writer: ^9.2.1

allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': true
  '@swc/core': true
  esbuild: true
  unrs-resolver: true

supportedArchitectures:
  os:
    - linux
    - darwin
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
minimumReleaseAge: 0
