const QUESTION_AUTHOR_ROLE_ADMIN = "admin";
const QUESTION_AUTHOR_ROLE_GAME = "game";
const QUESTION_AUTHOR_ROLE_AI = "ai";

const QUESTION_AUTHOR_ROLES = [
  QUESTION_AUTHOR_ROLE_ADMIN,
  QUESTION_AUTHOR_ROLE_GAME,
  QUESTION_AUTHOR_ROLE_AI,
] as const satisfies readonly string[];

const QUESTION_CREATION_AUTHOR_ROLES = [
  QUESTION_AUTHOR_ROLE_ADMIN,
  QUESTION_AUTHOR_ROLE_AI,
] as const satisfies readonly string[];

const QUESTION_AUTHOR_NAME_MIN_LENGTH = 3;

const QUESTION_AUTHOR_NAME_MAX_LENGTH = 30;

export {
  QUESTION_AUTHOR_ROLE_ADMIN,
  QUESTION_AUTHOR_ROLE_GAME,
  QUESTION_AUTHOR_ROLE_AI,
  QUESTION_AUTHOR_ROLES,
  QUESTION_CREATION_AUTHOR_ROLES,
  QUESTION_AUTHOR_NAME_MIN_LENGTH,
  QUESTION_AUTHOR_NAME_MAX_LENGTH,
};