export default {
  cleanTempDir: "always",
  incremental: true,
  incrementalFile: "tests/mutation/incremental/incremental.json",
  checkers: ["typescript"],
  tsconfigFile: "tsconfig.json",
  testRunner: "vitest",
  ignoreStatic: false,
  mutate: [
    "src/**/*.ts",
    "!**/*.spec.ts",
    "!**/*.schema.ts",
    "!**/*.constants.ts",
    "!**/*.module.ts",
    "!**/*.types.ts",
    "!**/*.commands.ts",
    "!**/*.contracts.ts",
  ],
  plugins: [
    "@stryker-mutator/vitest-runner",
    "@stryker-mutator/typescript-checker",
  ],
  ignorePatterns: [
    ".github/",
    ".husky/",
    ".output/",
    ".run/",
    ".idea/",
    "dist",
    "configs/",
    "!configs/vitest/vitest.config.ts",
    "tests/mutation",
    "tests/unit/coverage",
    "tests/acceptance",
    "scripts/",
    ".editorconfig",
    ".npmrc",
    ".DS_Store",
    "CHANGELOG.md",
    "LICENSE",
    "pnpm-lock.yaml",
    "sonar-project.properties",
    "README.md",
  ],
  vitest: {
    configFile: "configs/vitest/vitest.config.ts",
    related: true,
  },
  reporters: ["clear-text", "progress", "html", "json"],
  htmlReporter: { fileName: "tests/mutation/coverage/index.html" },
  jsonReporter: { fileName: "tests/mutation/coverage/mutation.json" },
  thresholds: {
    high: 100,
    low: 100,
    break: 100,
  },
  dryRunTimeoutMinutes: 10,
  typescriptChecker: {
    prioritizePerformanceOverAccuracy: true,
  },
  warnings: {
    slow: false,
  },
};