const API_KEY_HMAC_SECRET_MINIMAL_LENGTH = 32;

const API_KEY_MINIMAL_LENGTH = 24;

const API_KEY_HEADER = "goat-it-api-key";

export {
  API_KEY_HMAC_SECRET_MINIMAL_LENGTH,
  API_KEY_HEADER,
  API_KEY_MINIMAL_LENGTH,
};