const LOCALIZED_TEXT_ENTRY_MIN_LENGTH = 1;

const LOCALIZED_TEXT_ENTRY_MAX_LENGTH = 500;

const LOCALIZED_TEXTS_MIN_LENGTH = 1;

const LOCALIZED_TEXTS_MAX_LENGTH = 10;

export {
  LOCALIZED_TEXT_ENTRY_MIN_LENGTH,
  LOCALIZED_TEXT_ENTRY_MAX_LENGTH,
  LOCALIZED_TEXTS_MIN_LENGTH,
  LOCALIZED_TEXTS_MAX_LENGTH,
};