const QUESTION_THEME_STATUSES = ["active", "archived"] as const satisfies readonly string[];

const DEFAULT_QUESTION_THEME_STATUS = QUESTION_THEME_STATUSES[0];

const ARCHIVED_QUESTION_THEME_STATUS = QUESTION_THEME_STATUSES[1];

export {
  QUESTION_THEME_STATUSES,
  DEFAULT_QUESTION_THEME_STATUS,
  ARCHIVED_QUESTION_THEME_STATUS,
};