const QUESTION_STATUS_PENDING = "pending";
const QUESTION_STATUS_ACTIVE = "active";
const QUESTION_STATUS_ARCHIVED = "archived";
const QUESTION_STATUS_REJECTED = "rejected";

const QUESTION_STATUSES = [
  QUESTION_STATUS_PENDING,
  QUESTION_STATUS_ACTIVE,
  QUESTION_STATUS_ARCHIVED,
  QUESTION_STATUS_REJECTED,
] as const satisfies readonly string[];

const QUESTION_CREATION_STATUSES = [
  QUESTION_STATUS_PENDING,
  QUESTION_STATUS_ACTIVE,
] as const satisfies readonly string[];

export {
  QUESTION_STATUS_PENDING,
  QUESTION_STATUS_ACTIVE,
  QUESTION_STATUS_ARCHIVED,
  QUESTION_STATUS_REJECTED,
  QUESTION_STATUSES,
  QUESTION_CREATION_STATUSES,
};