const FIND_RANDOM_QUESTIONS_BODY_LIMIT_DEFAULT = 20;
const FIND_RANDOM_QUESTIONS_BODY_LIMIT_MINIMUM = 1;
const FIND_RANDOM_QUESTIONS_BODY_LIMIT_MAXIMUM = 50;
const FIND_RANDOM_QUESTIONS_BODY_LIMIT_DESCRIPTION = "Number of random questions to return.";

const FIND_RANDOM_QUESTIONS_BODY_EXCLUDED_IDS_MINIMUM = 1;
const FIND_RANDOM_QUESTIONS_BODY_EXCLUDED_IDS_MAXIMUM = 5000;

export {
  FIND_RANDOM_QUESTIONS_BODY_LIMIT_DEFAULT,
  FIND_RANDOM_QUESTIONS_BODY_LIMIT_MINIMUM,
  FIND_RANDOM_QUESTIONS_BODY_LIMIT_MAXIMUM,
  FIND_RANDOM_QUESTIONS_BODY_LIMIT_DESCRIPTION,
  FIND_RANDOM_QUESTIONS_BODY_EXCLUDED_IDS_MINIMUM,
  FIND_RANDOM_QUESTIONS_BODY_EXCLUDED_IDS_MAXIMUM,
};