name: Acceptance Tests ðŸ¥’
description: Run E2E acceptance tests and upload reports.
author: Antoine ZANARDI

inputs:
  acceptance-tests-reports-path:
    description: Path to acceptance tests reports (Cucumber JSON and HTML reports).
    required: true
    default: tests/acceptance/reports

outputs:
  acceptance-tests-count:
    description: Number of acceptance tests (scenarios) executed.
    value: ${{ steps.cucumber-results.outputs.acceptance-tests-count }}

runs:
  using: composite
  steps:
    - name: Install project ðŸ“¦
      uses: ./.github/actions/install-project

    - name: Acceptance tests âš—ï¸
      id: acceptance-tests
      continue-on-error: true
      shell: bash
      run: |
        pnpm run test:acceptance
        ${{ github.workspace }}/scripts/transform-cucumber-report-as-env-variables.sh >> "$GITHUB_ENV"

    - name: Set Cucumber Results As Outputs ðŸ“
      id: cucumber-results
      continue-on-error: true
      shell: bash
      run: echo "acceptance-tests-count=${{ env.CUCUMBER_SCENARIOS_COUNT }}" >> "$GITHUB_OUTPUT"

    - name: Save acceptance tests reports as artifact ðŸ’Ž
      uses: actions/upload-artifact@v4
      with:
        name: acceptance-tests-reports
        path: ${{ inputs.acceptance-tests-reports-path }}
        if-no-files-found: ignore
        retention-days: 2

    - name: Exit with error if acceptance tests failed ðŸš¨
      if: steps.acceptance-tests.outcome != 'success'
      shell: bash
      run: exit 1
