const ACCEPTANCE_TESTS_REPORTS_PATH = "tests/acceptance/reports";

const ACCEPTANCE_TESTS_REPORTS_SCREENSHOTS_PATH = `${ACCEPTANCE_TESTS_REPORTS_PATH}/screenshots`;

export {
  ACCEPTANCE_TESTS_REPORTS_PATH,
  ACCEPTANCE_TESTS_REPORTS_SCREENSHOTS_PATH,
};