const APP_HOST = "0.0.0.0";

const APP_PORT = 3000;

const APP_BASE_URL = `http://${APP_HOST}:${APP_PORT}`;

const APP_FORCE_KILL_TIMEOUT_MS = 5000;

const APP_HEALTH_OK_STATUS = 200;

const APP_HEALTH_RETRY_ATTEMPTS = 10;

const APP_HEALTH_RETRY_DELAY_MS = 100;

export {
  APP_HOST,
  APP_PORT,
  APP_BASE_URL,
  APP_FORCE_KILL_TIMEOUT_MS,
  APP_HEALTH_OK_STATUS,
  APP_HEALTH_RETRY_ATTEMPTS,
  APP_HEALTH_RETRY_DELAY_MS,
};