const APP_HOST = "0.0.0.0";

const APP_PORT = 3000;

const APP_BASE_URL = `http://${APP_HOST}:${APP_PORT}`;

const APP_READINESS_TIMEOUT_MS = 2500;

const APP_FORCE_KILL_TIMEOUT_MS = 5000;

const APP_KILL_TIMEOUT_MS = 10_000;

export {
  APP_HOST,
  APP_PORT,
  APP_BASE_URL,
  APP_READINESS_TIMEOUT_MS,
  APP_FORCE_KILL_TIMEOUT_MS,
  APP_KILL_TIMEOUT_MS,
};