import { APP_FORCE_KILL_TIMEOUT_MS } from "@acceptance-support/constants/app.constants";

const HOOKS_BEFORE_ALL_TIMEOUT_MS = 10_000;

const HOOKS_AFTER_ALL_TIMEOUT_BUFFER_MS = 10_000;

const HOOKS_AFTER_ALL_TIMEOUT_MS = APP_FORCE_KILL_TIMEOUT_MS + HOOKS_AFTER_ALL_TIMEOUT_BUFFER_MS;

export {
  HOOKS_BEFORE_ALL_TIMEOUT_MS,
  HOOKS_AFTER_ALL_TIMEOUT_MS,
};