const DEFAULT_ENV_SERVER_HOST = "0.0.0.0";

const MIN_PORT_NUMBER = 1;

const MAX_PORT_NUMBER = 65_535;

const DEFAULT_ENV_SERVER_PORT = 3000;

const DEFAULT_ENV_CORS_ORIGIN = "*";

const DEFAULT_ENV_MONGODB_HOST = "0.0.0.0";

const DEFAULT_ENV_MONGODB_PORT = 27_017;

const MONGODB_DATABASE_REGEX = /^[\w-]+(?<!-)$/u;

const DEFAULT_ENV_MONGODB_DATABASE = "goat-it";

export {
  DEFAULT_ENV_SERVER_HOST,
  DEFAULT_ENV_SERVER_PORT,
  MIN_PORT_NUMBER,
  MAX_PORT_NUMBER,
  DEFAULT_ENV_CORS_ORIGIN,
  DEFAULT_ENV_MONGODB_HOST,
  DEFAULT_ENV_MONGODB_PORT,
  MONGODB_DATABASE_REGEX,
  DEFAULT_ENV_MONGODB_DATABASE,
};