const DEFAULT_ENV_SERVER_HOST = "0.0.0.0";

const DEFAULT_ENV_SERVER_PORT = 3000;

const DEFAULT_ENV_CORS_ORIGIN = "*";

const DEFAULT_ENV_MONGODB_HOST = "localhost";

const DEFAULT_ENV_MONGODB_PORT = 27_017;

const DEFAULT_ENV_MONGODB_DATABASE = "goat-it";

export {
  DEFAULT_ENV_SERVER_HOST,
  DEFAULT_ENV_SERVER_PORT,
  DEFAULT_ENV_CORS_ORIGIN,
  DEFAULT_ENV_MONGODB_HOST,
  DEFAULT_ENV_MONGODB_PORT,
  DEFAULT_ENV_MONGODB_DATABASE,
};