const DATABASE_CONNECTION_TIMEOUT_MS = 5000;

const DATABASE_RETRY_DELAY_MS = 3000;

const DATABASE_RETRY_ATTEMPTS = 5;

const DATABASE_NAME = "goat-it";

export {
  DATABASE_CONNECTION_TIMEOUT_MS,
  DATABASE_RETRY_DELAY_MS,
  DATABASE_RETRY_ATTEMPTS,
  DATABASE_NAME,
};