const DATABASE_CONNECTION_TIMEOUT_MS = 5000;

const DATABASE_RETRY_DELAY_MS = 3000;

const DATABASE_RETRY_ATTEMPTS = 5;

export {
  DATABASE_CONNECTION_TIMEOUT_MS,
  DATABASE_RETRY_DELAY_MS,
  DATABASE_RETRY_ATTEMPTS,
};