const SLUG_REGEX = /^[\da-z]+(?:-[\da-z]+)*$/u;

const SLUG_MIN_LENGTH = 3;

const SLUG_MAX_LENGTH = 50;

const ISO_DATE_TIME_EXAMPLE = "2026-04-14T00:00:00.000Z";

export {
  SLUG_REGEX,
  SLUG_MIN_LENGTH,
  SLUG_MAX_LENGTH,
  ISO_DATE_TIME_EXAMPLE,
};