const DEFAULT_QUESTION_THEME_STATUS = "active";

const QUESTION_THEME_STATUS_ARCHIVED = "archived";

const QUESTION_THEME_STATUSES = [
  DEFAULT_QUESTION_THEME_STATUS,
  QUESTION_THEME_STATUS_ARCHIVED,
] as const satisfies readonly string[];

export {
  QUESTION_THEME_STATUSES,
  DEFAULT_QUESTION_THEME_STATUS,
  QUESTION_THEME_STATUS_ARCHIVED,
};