const QUESTION_STATUS_QUERY_KEY = "status";

const QUESTION_CATEGORY_QUERY_KEY = "category";

const QUESTION_COGNITIVE_DIFFICULTY_QUERY_KEY = "cognitive-difficulty";

const QUESTION_AUTHOR_ROLE_QUERY_KEY = "author-role";

const QUESTION_THEME_IDS_QUERY_KEY = "theme-ids";

export {
  QUESTION_STATUS_QUERY_KEY,
  QUESTION_CATEGORY_QUERY_KEY,
  QUESTION_COGNITIVE_DIFFICULTY_QUERY_KEY,
  QUESTION_AUTHOR_ROLE_QUERY_KEY,
  QUESTION_THEME_IDS_QUERY_KEY,
};