const RANDOM_QUESTIONS_LIMIT_DEFAULT = 20;
const RANDOM_QUESTIONS_LIMIT_MINIMUM = 1;
const RANDOM_QUESTIONS_LIMIT_MAXIMUM = 50;
const RANDOM_QUESTIONS_LIMIT_DESCRIPTION = "Number of random questions to return.";

export {
  RANDOM_QUESTIONS_LIMIT_DEFAULT,
  RANDOM_QUESTIONS_LIMIT_MINIMUM,
  RANDOM_QUESTIONS_LIMIT_MAXIMUM,
  RANDOM_QUESTIONS_LIMIT_DESCRIPTION,
};