const RANDOM_QUESTIONS_LIMIT_DEFAULT = 20;
const RANDOM_QUESTIONS_LIMIT_MINIMUM = 1;
const RANDOM_QUESTIONS_LIMIT_MAXIMUM = 50;
const RANDOM_QUESTIONS_LIMIT_DESCRIPTION = "Number of random questions to return.";

const RANDOM_QUESTIONS_EXCLUDED_IDS_QUERY_KEY = "excluded-ids";
const RANDOM_QUESTIONS_CATEGORIES_QUERY_KEY = "categories";
const RANDOM_QUESTIONS_COGNITIVE_DIFFICULTIES_QUERY_KEY = "cognitive-difficulties";

const RANDOM_QUESTIONS_EXCLUDED_IDS_MINIMUM = 1;
const RANDOM_QUESTIONS_EXCLUDED_IDS_MAXIMUM = 200;

export {
  RANDOM_QUESTIONS_LIMIT_DEFAULT,
  RANDOM_QUESTIONS_LIMIT_MINIMUM,
  RANDOM_QUESTIONS_LIMIT_MAXIMUM,
  RANDOM_QUESTIONS_LIMIT_DESCRIPTION,
  RANDOM_QUESTIONS_EXCLUDED_IDS_QUERY_KEY,
  RANDOM_QUESTIONS_CATEGORIES_QUERY_KEY,
  RANDOM_QUESTIONS_COGNITIVE_DIFFICULTIES_QUERY_KEY,
  RANDOM_QUESTIONS_EXCLUDED_IDS_MINIMUM,
  RANDOM_QUESTIONS_EXCLUDED_IDS_MAXIMUM,
};